In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import classification_report, accuracy_score

In [ ]:
df = pd.read_csv('02-16-2018.csv')

In [ ]:
df.info()

In [ ]:
traducciones = {
    'Dst Port': 'Puerto Destino',
    'Protocol': 'Protocolo',
    'Timestamp': 'Marca de Tiempo',
    'Flow Duration': 'Duración Flujo',
    'Tot Fwd Pkts': 'Total Paquetes Fwd',
    'Tot Bwd Pkts': 'Total Paquetes Bwd',
    'TotLen Fwd Pkts': 'Longitud Total Paquetes Fwd',
    'TotLen Bwd Pkts': 'Longitud Total Paquetes Bwd',
    'Fwd Pkt Len Max': 'Longitud Máxima Paquete Fwd',
    'Fwd Pkt Len Min': 'Longitud Mínima Paquete Fwd',
    'Fwd Pkt Len Mean': 'Longitud Media Paquete Fwd',
    'Fwd Pkt Len Std': 'Desviación Estándar Longitud Paquete Fwd',
    'Bwd Pkt Len Max': 'Longitud Máxima Paquete Bwd',
    'Bwd Pkt Len Min': 'Longitud Mínima Paquete Bwd',
    'Bwd Pkt Len Mean': 'Longitud Media Paquete Bwd',
    'Bwd Pkt Len Std': 'Desviación Estándar Longitud Paquete Bwd',
    'Flow Byts/s': 'Flujo Bytes/s',
    'Flow Pkts/s': 'Flujo Paquetes/s',
    'Flow IAT Mean': 'Media Tiempo Inter-Llegada Flujo',
    'Flow IAT Std': 'Desviación Estándar Tiempo Inter-Llegada Flujo',
    'Flow IAT Max': 'Máximo Tiempo Inter-Llegada Flujo',
    'Flow IAT Min': 'Mínimo Tiempo Inter-Llegada Flujo',
    'Fwd IAT Tot': 'Total Tiempo Inter-Llegada Fwd',
    'Fwd IAT Mean': 'Media Tiempo Inter-Llegada Fwd',
    'Fwd IAT Std': 'Desviación Estándar Tiempo Inter-Llegada Fwd',
    'Fwd IAT Max': 'Máximo Tiempo Inter-Llegada Fwd',
    'Fwd IAT Min': 'Mínimo Tiempo Inter-Llegada Fwd',
    'Bwd IAT Tot': 'Total Tiempo Inter-Llegada Bwd',
    'Bwd IAT Mean': 'Media Tiempo Inter-Llegada Bwd',
    'Bwd IAT Std': 'Desviación Estándar Tiempo Inter-Llegada Bwd',
    'Bwd IAT Max': 'Máximo Tiempo Inter-Llegada Bwd',
    'Bwd IAT Min': 'Mínimo Tiempo Inter-Llegada Bwd',
    'Fwd PSH Flags': 'Flags PSH Fwd',
    'Bwd PSH Flags': 'Flags PSH Bwd',
    'Fwd URG Flags': 'Flags URG Fwd',
    'Bwd URG Flags': 'Flags URG Bwd',
    'Fwd Header Len': 'Longitud Cabecera Fwd',
    'Bwd Header Len': 'Longitud Cabecera Bwd',
    'Fwd Pkts/s': 'Paquetes/s Fwd',
    'Bwd Pkts/s': 'Paquetes/s Bwd',
    'Pkt Len Min': 'Longitud Mínima Paquete',
    'Pkt Len Max': 'Longitud Máxima Paquete',
    'Pkt Len Mean': 'Longitud Media Paquete',
    'Pkt Len Std': 'Desviación Estándar Longitud Paquete',
    'Pkt Len Var': 'Varianza Longitud Paquete',
    'FIN Flag Cnt': 'Contador Flags FIN',
    'SYN Flag Cnt': 'Contador Flags SYN',
    'RST Flag Cnt': 'Contador Flags RST',
    'PSH Flag Cnt': 'Contador Flags PSH',
    'ACK Flag Cnt': 'Contador Flags ACK',
    'URG Flag Cnt': 'Contador Flags URG',
    'CWE Flag Count': 'Contador Flags CWE',
    'ECE Flag Cnt': 'Contador Flags ECE',
    'Down/Up Ratio': 'Ratio Descarga/Subida',
    'Pkt Size Avg': 'Tamaño Promedio Paquete',
    'Fwd Seg Size Avg': 'Tamaño Promedio Segmento Fwd',
    'Bwd Seg Size Avg': 'Tamaño Promedio Segmento Bwd',
    'Fwd Byts/b Avg': 'Promedio Bytes/b Fwd',
    'Fwd Pkts/b Avg': 'Promedio Paquetes/b Fwd',
    'Fwd Blk Rate Avg': 'Promedio Tasa Bloque Fwd',
    'Bwd Byts/b Avg': 'Promedio Bytes/b Bwd',
    'Bwd Pkts/b Avg': 'Promedio Paquetes/b Bwd',
    'Bwd Blk Rate Avg': 'Promedio Tasa Bloque Bwd',
    'Subflow Fwd Pkts': 'Paquetes Fwd Subflujo',
    'Subflow Fwd Byts': 'Bytes Fwd Subflujo',
    'Subflow Bwd Pkts': 'Paquetes Bwd Subflujo',
    'Subflow Bwd Byts': 'Bytes Bwd Subflujo',
    'Init Fwd Win Byts': 'Bytes Iniciales Ventana Fwd',
    'Init Bwd Win Byts': 'Bytes Iniciales Ventana Bwd',
    'Fwd Act Data Pkts': 'Paquetes Datos Fwd Activos',
    'Fwd Seg Size Min': 'Tamaño Mínimo Segmento Fwd',
    'Active Mean': 'Media Actividad',
    'Active Std': 'Desviación Estándar Actividad',
    'Active Max': 'Máximo Actividad',
    'Active Min': 'Mínimo Actividad',
    'Idle Mean': 'Media Inactividad',
    'Idle Std': 'Desviación Estándar Inactividad',
    'Idle Max': 'Máximo Inactividad',
    'Idle Min': 'Mínimo Inactividad',
    'Label': 'Etiqueta'}

In [ ]:
df = df.rename(columns=traducciones)

In [ ]:
df['Marca de Tiempo'] = pd.to_datetime(df['Marca de Tiempo'], format='%d/%m/%Y %H:%M:%S', errors='coerce')

In [ ]:
df.head()

,Puerto Destino,Protocolo,Marca de Tiempo,Duración Flujo,Total Paquetes Fwd,Total Paquetes Bwd,Longitud Total Paquetes Fwd,Longitud Total Paquetes Bwd,Longitud Máxima Paquete Fwd,Longitud Mínima Paquete Fwd,...,Tamaño Mínimo Segmento Fwd,Media Actividad,Desviación Estándar Actividad,Máximo Actividad,Mínimo Actividad,Media Inactividad,Desviación Estándar Inactividad,Máximo Inactividad,Mínimo Inactividad,Etiqueta
0,0,0,2018-02-16 08:27:23,112640768,3,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,56300000.0,138.592929,56300000.0,56300000.0,Benign
1,0,0,2018-02-16 08:30:12,112641773,3,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,56300000.0,263.750829,56300000.0,56300000.0,Benign
2,35605,6,2018-02-16 08:26:55,20784143,23,44,2416,1344,240,64,...,20.0,2624734.0,0.0,2624734.0,2624734.0,9058214.0,0.000000,9058214.0,9058214.0,Benign
3,0,0,2018-02-16 08:33:01,112640836,3,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,56300000.0,82.024387,56300000.0,56300000.0,Benign
4,23,6,2018-02-16 08:27:59,20,1,1,0,0,0,0,...,20.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,Benign

In [ ]:
df.info()

In [ ]:
df['Etiqueta'].astype(str)

0                   Benign
1                   Benign
2                   Benign
3                   Benign
4                   Benign
                ...
729176              Benign
729177    DoS attacks-Hulk
729178    DoS attacks-Hulk
729179    DoS attacks-Hulk
729180                 nan
Name: Etiqueta, Length: 729181, dtype: object

In [ ]:
df['Etiqueta'] = df['Etiqueta'].str.strip().str.lower()

In [ ]:
df['Etiqueta']

0                   benign
1                   benign
2                   benign
3                   benign
4                   benign
                ...
729176              benign
729177    dos attacks-hulk
729178    dos attacks-hulk
729179    dos attacks-hulk
729180                 NaN
Name: Etiqueta, Length: 729181, dtype: object

In [ ]:
df.fillna(0, inplace=True)

In [ ]:
df['Media Tiempo Inter-Llegada Flujo'] = df['Media Tiempo Inter-Llegada Flujo'].fillna(df['Media Tiempo Inter-Llegada Flujo'].mean())

In [ ]:
print(df['Etiqueta'].isnull().sum())

0

In [ ]:
df = df.dropna(subset=['Etiqueta'])

In [ ]:
df['Etiqueta'] = df['Etiqueta'].astype('category')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 729180 entries, 0 to 729179
Data columns (total 80 columns):
 #   Column                                          Non-Null Count   Dtype
---  ------                                          --------------   -----
 0   Puerto Destino                                  729180 non-null  int64
 1   Protocolo                                       729180 non-null  int64
 2   Marca de Tiempo                                 729180 non-null  datetime64[ns]
 3   Duración Flujo                                  729180 non-null  int64
 4   Total Paquetes Fwd                              729180 non-null  int64
 5   Total Paquetes Bwd                              729180 non-null  int64
 6   Longitud Total Paquetes Fwd                     729180 non-null  int64
 7   Longitud Total Paquetes Bwd                     729180 non-null  int64
 8   Longitud Máxima Paquete Fwd                     729180 non-null  int64
 9   Longitud Mínima Paquete Fwd                     729180 non-null  int64
 10  Longitud Media Paquete Fwd                      729180 non-null  float64
 11  Desviación Estándar Longitud Paquete Fwd        729180 non-null  float64
 12  Longitud Máxima Paquete Bwd                     729180 non-null  int64
 13  Longitud Mínima Paquete Bwd                     729180 non-null  int64
 14  Longitud Media Paquete Bwd                      729180 non-null  float64
 15  Desviación Estándar Longitud Paquete Bwd        729180 non-null  float64
 16  Flujo Bytes/s                                   729180 non-null  float64
 17  Flujo Paquetes/s                                729180 non-null  float64
 18  Media Tiempo Inter-Llegada Flujo                729180 non-null  float64
 19  Desviación Estándar Tiempo Inter-Llegada Flujo  729180 non-null  float64
 20  Máximo Tiempo Inter-Llegada Flujo               729180 non-null  int64
 21  Mínimo Tiempo Inter-Llegada Flujo               729180 non-null  int64
 22  Total Tiempo Inter-Llegada Fwd                  729180 non-null  int64
 23  Media Tiempo Inter-Llegada Fwd                  729180 non-null  float64
 24  Desviación Estándar Tiempo Inter-Llegada Fwd    729180 non-null  float64
 25  Máximo Tiempo Inter-Llegada Fwd                 729180 non-null  int64
 26  Mínimo Tiempo Inter-Llegada Fwd                 729180 non-null  int64
 27  Total Tiempo Inter-Llegada Bwd                  729180 non-null  int64
 28  Media Tiempo Inter-Llegada Bwd                  729180 non-null  float64
 29  Desviación Estándar Tiempo Inter-Llegada Bwd    729180 non-null  float64
 30  Máximo Tiempo Inter-Llegada Bwd                 729180 non-null  float64
 31  Mínimo Tiempo Inter-Llegada Bwd                 729180 non-null  float64
 32  Flags PSH Fwd                                   729180 non-null  float64
 33  Flags PSH Bwd                                   729180 non-null  float64
 34  Flags URG Fwd                                   729180 non-null  float64
 35  Flags URG Bwd                                   729180 non-null  float64
 36  Longitud Cabecera Fwd                           729180 non-null  float64
 37  Longitud Cabecera Bwd                           729180 non-null  float64
 38  Paquetes/s Fwd                                  729180 non-null  float64
 39  Paquetes/s Bwd                                  729180 non-null  float64
 40  Longitud Mínima Paquete                         729180 non-null  float64
 41  Longitud Máxima Paquete                         729180 non-null  float64
 42  Longitud Media Paquete                          729180 non-null  float64
 43  Desviación Estándar Longitud Paquete            729180 non-null  float64
 44  Varianza Longitud Paquete                       729180 non-null  float64
 45  Contador Flags FIN                              729180 non-null  float64
 46  Contador Flags SYN                              729180 non-null  float64
 47  Contador Flags RST                              729180 non-null  float64
 48  Contador Flags PSH                              729180 non-null  float64
 49  Contador Flags ACK                              729180 non-null  float64
 50  Contador Flags URG                              729180 non-null  float64
 51  Contador Flags CWE                              729180 non-null  float64
 52  Contador Flags ECE                              729180 non-null  float64
 53  Ratio Descarga/Subida                           729180 non-null  float64
 54  Tamaño Promedio Paquete                         729180 non-null  float64
 55  Tamaño Promedio Segmento Fwd                    729180 non-null  float64
 56  Tamaño Promedio Segmento Bwd                    729180 non-null  float64
 57  Promedio Bytes/b Fwd                            729180 non-null  float64
 58  Promedio Paquetes/b Fwd                         729180 non-null  float64
 59  Promedio Tasa Bloque Fwd                        729180 non-null  float64
 60  Promedio Bytes/b Bwd                            729180 non-null  float64
 61  Promedio Paquetes/b Bwd                         729180 non-null  float64
 62  Promedio Tasa Bloque Bwd                        729180 non-null  float64
 63  Paquetes Fwd Subflujo                           729180 non-null  float64
 64  Bytes Fwd Subflujo                              729180 non-null  float64
 65  Paquetes Bwd Subflujo                           729180 non-null  float64
 66  Bytes Bwd Subflujo                              729180 non-null  float64
 67  Bytes Iniciales Ventana Fwd                     729180 non-null  float64
 68  Bytes Iniciales Ventana Bwd                     729180 non-null  float64
 69  Paquetes Datos Fwd Activos                      729180 non-null  float64
 70  Tamaño Mínimo Segmento Fwd                      729180 non-null  float64
 71  Media Actividad                                 729180 non-null  float64
 72  Desviación Estándar Actividad                   729180 non-null  float64
 73  Máximo Actividad                                729180 non-null  float64
 74  Mínimo Actividad                                729180 non-null  float64
 75  Media Inactividad                               729180 non-null  float64
 76  Desviación Estándar Inactividad                 729180 non-null  float64
 77  Máximo Inactividad                              729180 non-null  float64
 78  Mínimo Inactividad                              729180 non-null  float64
 79  Etiqueta                                        729180 non-null  category
dtypes: category(1), datetime64[ns](1), float64(61), int64(17)
memory usage: 445.8 MB

Los modelos de ML no pueden procesar la fecha (Marca de Tiempo), así que debemos excluirla o convertirla. También necesitamos separar tus datos en X (variables predictoras) e y (tu columna Etiqueta). en este caso eliminaremos esta columna

In [ ]:
#eliminamos la culmna de marca de tiempo
X = df.drop(['Marca de Tiempo', 'Etiqueta'], axis=1)

In [ ]:
# Convertimos en un diccionario los valores de Etiqueta para poder utilizarlos como referencias para nuestro modelo
codigo_mapeo = dict(enumerate(df['Etiqueta'].cat.categories))
print(codigo_mapeo)

{0: 'benign', 1: 'dos attacks-hulk', 2: 'dos attacks-slowhttptest'}

In [ ]:

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
scaler = StandardScaler()

# Escalamos directamente porque X_train y X_test ya no tienen la columna 'Etiqueta'
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [ ]:
# Usamos X_train_scaled porque ya pasaron por el StandardScaler
log_model = LogisticRegression(max_iter=1000)
log_model.fit(X_train_scaled, y_train)

# Predicción
y_pred_log = log_model.predict(X_test_scaled)

In [ ]:
nb_model = GaussianNB()
nb_model.fit(X_train_scaled, y_train)

# Predicción
y_pred_nb = nb_model.predict(X_test_scaled)

In [ ]:
print("Resultados Regresión Logística:")
print(classification_report(y_test, y_pred_log, target_names=df['Etiqueta'].cat.categories))

print("\nResultados Naive Bayes:")
print(classification_report(y_test, y_pred_nb, target_names=df['Etiqueta'].cat.categories))

Resultados Regresión Logística:
                          precision    recall  f1-score   support

                  benign       1.00      1.00      1.00     61823
        dos attacks-hulk       1.00      1.00      1.00     65772
dos attacks-slowhttptest       1.00      1.00      1.00     18241

                accuracy                           1.00    145836
               macro avg       1.00      1.00      1.00    145836
            weighted avg       1.00      1.00      1.00    145836


Resultados Naive Bayes:
                          precision    recall  f1-score   support

                  benign       1.00      1.00      1.00     61823
        dos attacks-hulk       1.00      1.00      1.00     65772
dos attacks-slowhttptest       1.00      1.00      1.00     18241

                accuracy                           1.00    145836
               macro avg       1.00      1.00      1.00    145836
            weighted avg       1.00      1.00      1.00    145836

In [ ]:
importances = pd.Series(log_model.coef_[0], index=X.columns)
print(importances.sort_values(ascending=False).head(10))

Puerto Destino                 4.870634
Longitud Total Paquetes Bwd    0.618237
Bytes Bwd Subflujo             0.618237
Paquetes Datos Fwd Activos     0.594847
Total Paquetes Fwd             0.541090
Paquetes Fwd Subflujo          0.541090
Paquetes Bwd Subflujo          0.506544
Total Paquetes Bwd             0.506544
Longitud Cabecera Bwd          0.491024
Longitud Cabecera Fwd          0.427362
dtype: float64

División de datos
train_test_split: Se usa justo antes del entrenamiento para separar X_train (lo que el modelo estudia) y X_test (el examen final).

Escalado
StandardScaler:

scaler = StandardScaler(): Crea la herramienta.

scaler.fit_transform(X_train): "Aprende" el promedio y la escala de tus datos de entrenamiento.

scaler.transform(X_test): Aplica esa misma escala a los datos nuevos para que coincidan.

Entrenamiento y Predicción
LogisticRegression / GaussianNB:

model.fit(...): Aquí es donde ocurre el "aprendizaje". El modelo analiza la relación entre las columnas y la Etiqueta.

model.predict(...): Aquí el modelo recibe datos nuevos y adivina si son benignos o ataques.

Evaluación
classification_report: Es el que usaste para generar ese reporte con precisión 1.00. Te da la foto completa de si el modelo se confunde entre tipos de ataques.